from .index import *
from .game_detail import *
from .game_list import *
from .forum_home import *
from .login import *
from .register import *
from .post_create import *
from .post_detail import *
from .game_create import *
